---
title: A practical guide to Promises
description: Everything you need to know about Promises to be productive
---

_This is part of an on-going series around concurrent programming in the browser
and Node.js_

## Promises

When programming in JavaScript, you may have come across a primitive
known as a **Promise**. A Promise is useful for representing the result of
something that will take a very long time. Often, this kind of operation would
involve network requests, performing expensive operations, or interacting with
the file system.

However, a Promise is intentionally generic. This means that you can use them
in any number of ways for your own tasks, and not exclusively when working with
APIs in the browser or Node.js.

You can create a Promise by using the `Promise` constructor:

```js
const promise = new Promise((resolve, reject) => resolve(1));
```

However, this does not seem particularly useful <span aria-label="laughing">ðŸ˜‚</span>
What are we supposed to use this for?

### Our first promise

One of my favorite examples when thinking about promises is to use them to
create a `sleep` function. Our `sleep` function will build upon the `Promise`
constructor approach above. It will also use `setTimeout` to wait some amount of time
before calling `resolve`.

One implementation of this `sleep` function may look like:

```js
/**
 * Sleep for the specified time, given in milliseconds
 * @param {number} ms - the number of milliseconds to wait
 * @returns {Promise<void>}
 */
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

We can use this `Promise`-returning function by using the `then` method that is
available on the `Promise` prototype. With our `sleep` function above, this
looks like:

```js
// `sleep` returns a Promise with a `then` method we can call
sleep(1000).then(() => {
  console.log('Called after 1000ms!');
});
```

The `then` method takes in a function that is called when the `Promise` returned
by `sleep` finally is resolved. But wait, what does it mean for a Promise to be
_resolved_ <span aria-label="thinking">ðŸ¤”</span>?

### The states of a Promise

It turns out that a Promise can be in one of three states: pending, fulfilled,
and rejected.

<!-- prettier-ignore-start -->
*Note: there is a great diagram of this over on [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global\_Objects/Promise#Description)*
<!-- prettier-ignore-end -->

When we create a Promise using the `Promise` constructor it immediately moves to
the _pending_ state. This promise can then transition to either a _fulfilled_ or
_rejected_ state through the `executor` function that is given to the `Promise`
constructor.

The `executor` function is another way of describing the callback function given
to `Promise` that takes in two arguments: `resolve` and `reject`. Looking at
our example above:

```js
const promise = new Promise((resolve, reject) => resolve(1));

// Let's also use `then` to get the value of this promise
promise.then(value => {
  console.log(value); // 1
});
```

Our `executor` function takes in `resolve` and `reject` and then immediately
calls `resolve` with the value `1`. Calling `resolve` transitions the promise
to a fulfilled state which in turn will call the callback function given to the
`then` function.

However, sometimes the callback given to `then` may have to wait a bit before
being called. If we used our `sleep` function from above we would see that the
callback would have to wait at least 1000 milliseconds before being called.

```js
sleep(1000).then(() => {
  console.log('Called after 1000ms!');
});
```

#### Handling errors

On the other hand, if our `executor` function runs into a problem, or itself
triggers an exception, we need a way to catch any kind of errors that happen as
a result of this computation. This is where the `reject` and `catch` methods
become insanely useful.

If we changed our initial example to instead call `reject` with an error, we
would see something like:

```js
const promise = new Promise((resolve, reject) =>
  reject(new Error('Something went wrong!'))
);

promise.then(onFulfilled).catch(onRejected);
// The above is roughly equivalent to the following:
promise.then(onFulfilled, onRejected);
```

Here, `onFulfilled` and `onRejected` would be the methods called with the result
of `resolve` or `reject`, respectively. We can now use the `catch` method
available on the `Promise` prototype to catch any errors that happen while
trying to run the `executor` function for the Promise.

### Chaining promises

Now that we have a better understanding of Promises, their states, and how we
can use the results of a promise becoming fulfilled or rejected, let's explore
more about how we can use promises together.

Something that's interesting about `then` and `catch` is that **we can chain
them together**. In other words, we can keep calling `then` and `catch` even
after the first call.

If we used our `sleep` function from above we could create a chain by doing:

```js
sleep(1000)
  .then(() => console.log('called after 1000ms'))
  .then(() => console.log('called after the first `then` runs'))
  .then(() => console.log('wow, why are we still chaining these?'));
```

While we are just chaining `console.log` calls here, something that is great
about this is that if we return a `Promise` from the callback passed to `then`
we can get the value of this promise in the next `then` in the chain.

This is most helpful to visualize alongside a method on the `Promise` object
called `Promise.resolve`. This function will create a `Promise` that resolves to
the value we supply to it. Using it in a promise chain, we can see how values
from promises flow in the chain:

```js
// Returns a promise that will resolve with the value `1`
Promise.resolve(1)
  .then(value => {
    console.log(value); // 1
    return Promise.resolve(2);
  })
  .then(value => {
    console.log(value); // 2
    return Promise.resolve(3);
  })
  .then(value => {
    console.log(value); // 3
  });
```

We can chain `catch` calls in a similar way:

```js
// Returns a promise that will reject with an error
Promise.reject(new Error('error message'))
  .catch(error => {
    console.error(error); // 'error message'
    return Promise.resolve(1);
  })
  .then(value => {
    console.log(value); // 1;
    return Promise.reject(new Error('another error'));
  })
  .catch(error => {
    console.error(error); // 'another error'
  });
```

Chaining is great in these situations where we can chain results and not have to
worry about previous results. However, sometimes we might be building out a
feature where we need to know about previous results. Maybe we're working on a
weather status page that can get the user's current location and fetch from an
API the weather for that location.

In this case, we will want to both use the current location and the results of
the weather at the location to put something relevant on the screen for the
user. Maybe something like:

```js
function displayWeatherResults(location, weather) {
  return `The current weather in ${location} is ${weather}.`;
}
```

At a high-level, the code to fetch this information might look like:

```js
getCurrentLocation()
  .then(location => {
    return getWeatherFor(location);
  })
  .catch(errorGettingUser => /* ... */)
  .then(weather => {
    // Only have access to weather in this callback ðŸ˜¬
  })
```

How do orchestrate situations like these where results may funnel into other
results or operations we need to perform?

### `async` Functions

JavaScript added a new type of function called an `AsyncFunction` in ES2015.

_As an aside, can we talk about how crazy it is that there are more than one
type of function?!_

An `AsyncFunction` is a special type of function that implicitly returns a
`Promise`. You can make an `AsyncFunction` by adding the `async` keyword before
defining your function. This works for function declarations, expressions, and
even arrow functions!

For example:

```js
async function main() {
  // ...
}

main()
  .then(result => /* ... */)
  .catch(error => /* ... */);
```

These `AsyncFunction`s are special because they also give us access to another
keyword: `await`. The `await` keyword can feel like a superpower in JavaScript
because it allows us to write asynchronous code in a way that feels identical to
how we would write code normally.

We could translate our weather example from above to an `AsyncFunction` by
writing:

```js
async function main() {
  const location = await getCurrentLocation();
  const weather = await getWeatherFor(location);

  displayWeatherResults(location, weather);
}

main()
  .then(result => /* ... */)
  .catch(error => /* ... */);
```

Now, instead of chaining our promises and potentially not having access to a
previous value we can write our code similar to how we would without any
promises and it just works as expected.

_Jafar Husain has a great talk on this syntax difference available [on YouTube](https://www.youtube.com/watch?v=lil4YCCXRYc)_

### `Promise` methods

#### Running promises in parallel

#### Waiting for fastest promise to resolve

##### Timeouts

<!-- While the -->
<!-- Promise is pending, any calls to `then` are delayed until the Promise moves to -->
<!-- either `fulfilled` or `rejected`. -->

<!-- A Promise becomes `fulfilled` or `rejected` through the two arguments `resolve` -->
<!-- and `reject` that are passed to the function given to the `Promise` constructor. -->
